### ISSUE TITLE
please change the flatpak icon

### ISSUE THREAD

**Issue by umlaeute** [agraef/purr-data#26]
Purr Data is available via flatpak (great), but it's icon looks suspiciously identical to Pd's icon.

https://github.com/agraef/purr-data/blob/master/packages/linux_flatpak/net.purrdata.PurrData.svg

since Purr-Data is similar to Pd, but is *not* the same as Pd, I would like to ask you to fix the icon (hey: Purr has a great icon of it's own!).

this has become more of an issue since Pd(vanilla) now is also available as a flatpak application: https://flathub.org/apps/search?q=puredata

this is a reboot of https://github.com/flathub/net.purrdata.PurrData/issues/1 (which was opened in 2019(!), and it seems that there was even a thread on the mailinglist about this in the same year; it seems the question of the icon has stalled since then)

PS: i would have opened this directly on https://git.purrdata.net/jwilkes/purr-data/, but it seems my account creation has not been accepted for a couple of days...

**Comment by agraef** [comment]
Oops. I didn't even know that there was a Purr Data flatpak out in the wild. @ssssam It seems that you committed this in 2019, can you please have a look? Or at least tell me what changes are needed? Is it enough to just change the svg icon in purr-data/packages/linux_flatpak/?

**Comment by agraef** [comment]
@ssssam, I converted our 128x128 png icon to svg, here it is:

![purr-data](https://github.com/agraef/purr-data/assets/2853977/cf8d0a01-f422-4461-8821-a2fb301551ee)

Would that be good enough?

**Comment by umlaeute** [comment]
@agraef isn't this the icon of Pd-extended?

i think it would be great if https://flathub.org/apps/search?q=puredata showed 3 different application icons.

what's wrong with the cat?

**Comment by ssssam** [comment]
updating the icon in the Git repo should be enough, yes. I think the ideal might be the cat overlayed ontop of the Pd extended logo ... I probably have that on a long-lost todo list somewhere..

**Comment by agraef** [comment]
I'm no artist. Ok, I'll report it upstream, maybe Jonathan can do something about it.

**Comment by agraef** [comment]
The cat icons we have are simply too small for that purpose. I vaguely recall that Joseph posted something like what @ssssam suggested quite a while ago, but I don't remember where or when, and I can't find that post in my mailbox either. :(

**Comment by umlaeute** [comment]
we would need a proper scalable SVG version of the icon.

- http://disis.music.vt.edu/pipermail/l2ork-dev/2019-November/002276.html
- http://disis.music.vt.edu/pipermail/l2ork-dev/2023-August/003989.html

**Comment by agraef** [comment]
I talked to Jonathan about this, and he thinks he still has at least a larger version of the cat icon that we can use.

**Comment by umlaeute** [comment]
here's an SVG generated from a cat image using [autotrace](https://github.com/autotrace/autotrace)

![purr](https://github.com/agraef/purr-data/assets/214034/74cfa716-0e17-425d-ad57-08eba8f663f6)


i'm no artist either (and while i kind of like the deconstructivst outcome, there's no obvious "design" reason for it; and of course it looks like it come right out of your favorite photoshop effect...)

**Comment by Baizkunthaz** [comment]
Hey guys, I'm sorry to interrupt, but is this the real purr data organization's GitHub account?

**Comment by agraef** [comment]
Well, kind of. It's the official GH mirror of Jonathan's Gitlab where we keep all of our releases (Jonathan's own CI setup has been largely dysfunctional for some time, so I took over and created a CI setup here). It also has a GH page so that it becomes easier to find stuff.

@umlaeute Sorry for getting back so late, I haven't forgotten about the issue, and I actually talked to Jonathan about this during our GSoC and he promised to look into this at the time. But apparently for got about it, so I'll remind him again.

**Comment by Baizkunthaz** [comment]
Ok @agraef so I want to contribute to purr data, so from where could I start?

**Comment by umlaeute** [comment]
@agraef thanks

**Comment by umlaeute** [comment]
@Baizkunthaz how about checking out the [README](https://github.com/agraef/purr-data#contributor-guide) rather than hijacking a completely unrelated thread? If you think you need a more discussion-like interaction than a plain README, you can also open up your own issue.

**Comment by Baizkunthaz** [comment]
Ok @umlaeute I am sorry for the inconvenience. Actually, I am new to open source, so that's why I asked; otherwise, my intentions weren't just to hijack the unrelated thread.

**Comment by agraef** [comment]
@Baizkunthaz: @umlaeute is right, this is not the right place. There's the DISIS mailing list (l2ork-dev, link is in the README), and you can contact me directly (aggraef at gmail.com). Make sure that you have a look at the codebase (it's complicated, and involves a lot of C/C++), and try to figure out which areas you could and would like to contribute to.

**Comment by agraef** [comment]
Unfortunately, Jonathan never sent me anything. I can only assume that either the svg originals have been lost or that he doesn't want to share them.

Anyway, to bring this ticket to some kind of resolution, I now replaced the vanilla icon in packages/linux_flatpak with our 128x128 png icon converted to svg, as I suggested earlier. Yes, this is the Pd-extended icon, but then so be it -- Pd-extended has been dead since 2014 and even puredata.info says that you shouldn't use it anymore. :) Sorry folks, but that's the best I can do.

I didn't touch any of the other stuff in packages/linux_flatpak, as I'm not familiar with flatpak and have no time to learn it either -- to much other things to do, and live is short.

@ssssam I see that you're still updating the package on flathub, could you please update the icon in that package with [packages/linux_flatpak/net.purrdata.PurrData.svg](https://github.com/agraef/purr-data/raw/testing/packages/linux_flatpak/net.purrdata.PurrData.svg)? That would be much appreciated. Also, I'd *really* appreciate it if you could send me a PR to update the contents of packages/linux_flatpak with what you have on flathub some time. And I'd be *really* very, *very* thankful if you could add some more elaborate instructions to the README there so that even an idiot like me can figure out how to build the thing locally. ;-) Because the the instructions there don't work for me.

**Comment by umlaeute** [comment]
note that there *is* a Pd-extended package available on flathub (which of course uses the Pd-extended SVG) : https://flathub.org/apps/info.puredata.Pd-extended

i agree that Pd-extended is dead and probably should be left there.
i have no idea why @eighthave resurrected just for the flathub packages...

**Comment by agraef** [comment]
Yes, I know. But until a graphic artist steps in and helps me out with this, it's the best I can do.

**Comment by agraef** [comment]
Ok, I just gave it another whirl, using small_cat.png with added transparency as a base. Here's how that looks like when placed above the extended icon:

![purr-data](https://github.com/user-attachments/assets/94b4c762-d9c1-4747-9377-c57503b9d7a5)

Not too shabby... Or how about this:

![small_cat](https://github.com/user-attachments/assets/d3bf3003-bf89-4960-b6bf-8484f8c5d3cd)

The latter one is probably too bad in resolution, but the former might do the job. Opinions?

**Comment by eighthave** [comment]
Hey all!  Love to see Pd going strong!  I put Pd-extended up on Flathub for 
anyone who needs it for projects that were built with it.  I personally use it, 
for example.  I have no plans of making any other packages, e.g. macOS, Windows, 
etc.

**Comment by umlaeute** [comment]
> The latter one is probably too bad in resolution, but the former might do the job. Opinions?

how about replacing the [bng] with the cat?

**Comment by agraef** [comment]
Hi @eighthave, thanks for stopping by! I didn't know that it is you who maintains that flatpak. It's amazing that you can still run Pd-extended that way on a modern system. It does indeed run on my Manjaro system running Pipewire, even Jack audio and MIDI work fine. Gem, zexy, and pdp won't load, however, but I guess that this is because they don't seem to be included in the package AFAICT.

**Comment by umlaeute** [comment]
> how about replacing the [bng] with the cat?
> 
> Not sure how you imagine that to look like, but in any case I'm not capable of doing it. :)

Me probably neither. 

Do you have the small cat as a "real" SVG as well? (It seems that this is currently just a PNG/bitmap embedded in an SVG, but the design looks as if it could easily be done in pure vector graphics)

**Comment by umlaeute** [comment]
> Ok, I wasn't aware that pd-extended was still being used that much

I don't think it is used "that much" (without having any numbers, my gut feeling feels me that most downloads on flathub are probably mistakes, as it is more shiny, and more "extended" than the other options (vanilla, purr, l2ork)), but I guess it makes sense from a coffee preservation POV.

**Comment by agraef** [comment]
> It seems that this is currently just a PNG/bitmap embedded in an SVG

That's what it is. As I said, I don't have any of Jonathan's original vector images, so I took the small_cat.bmp from the win64_inno folder, added transparent background in the GIMP, exported that to png, imported that png in Inkscape, and finally saved it as an svg. That kind of workflow works best for me, I know that there are online png->svg converters but the ones I know are all rubbish. :)
