### ISSUE TITLE
Outdated and inaccurate information about Linux build dependencies in the README

### ISSUE THREAD

**Issue by agraef** [agraef/purr-data#43]
Apparently these are an obstacle for some users at least. I'm not sure how easy it would be to keep these in sync with the debuild/debian/control file, maybe we need a script to re-generate this section from time to time?

**Comment by 092vk** [comment]
Hello @agraef,

I’m the one who created issue #32 regarding updating the Linux section in the README.md file. I wanted to clarify the approach:

Should I only update the README.md file with the latest list of dependencies, or should I also create a script that regenerates this section periodically? My understanding is that the script would ensure that the list of dependencies in the README.md is always up-to-date, automating the process rather than manually updating the file.

Could you please confirm if this approach aligns with your expectations or if you have any other recommendations? I have some experience with cron jobs, but I would need your help to automate the script.

Additionally, I am working on two more issues listed in the GSOC idea list for 2024:

1.Purr Data Message and DSP Profiler
2.Profile Purr Data CPU Usage in Real-Time

Could you provide me with more details regarding these issues and let me know if I can work on them?

Thank you!

**Comment by 092vk** [comment]
Hello @agraef,

I’m the one who created issue #32 regarding updating the Linux section in the README.md file. I wanted to clarify the approach:

Should I only update the README.md file with the latest list of dependencies, or should I also create a script that regenerates this section periodically? I have already resolved this issue, so please let me know which approach aligns with your expectations so I can create a PR.

Additionally, I am working on two more issues listed in the GSOC idea list for 2024:

1.Purr Data Message and DSP Profiler
2.Profile Purr Data CPU Usage in Real-Time

Could you let me know if I can work on these issues or if they have already been resolved?

Thank you!
