### ISSUE TITLE
I can't run 2.20 on mac

### ISSUE THREAD

**Issue by porres** [agraef/purr-data#55]
trying on macbook air M3 Sonoma

when trying the download from https://github.com/agraef/purr-data/releases/tag/2.20.0 I get

<img width="308" alt="Screenshot 2024-10-16 at 03 10 07" src="https://github.com/user-attachments/assets/446432bc-5c42-4c95-b8c6-d59acdbd27f1">

**Comment by agraef** [comment]
This looks like a Gatekeeper problem (the application isn't notarized), see https://github.com/agraef/purr-data/wiki/Installation#notes-on-gatekeeper.

Also, on Apple Silicon you need to have Rosetta 2 installed, as our binary is for x86_64.

**Comment by agraef** [comment]
I can't offer a universal binary until #22 has been resolved. While the light build works, there are a number of libraries which crash when built natively for Apple Silicon. This is on my TODO list, but it will be a substantial amount of work, and since the x86_64 version works fine in Rosetta, it doesn't have top priority right now.

OTOH, I can't offer a notarized binary since that requires an Apple Developer membership which would cost me my own money, or at least a substantial amount of paperwork to get a fee waiver which I'm not inclined to bother with -- I have better things to do in my spare time.

**Comment by agraef** [comment]
In case the installation instructions weren't clear enough: You only need to run this sudo command in a terminal, then the app should launch fine afterwards:

~~~shell
sudo xattr -r -d com.apple.quarantine /Applications/Purr-Data.app
~~~

If you launch the app for the first time and you don't have Rosetta installed, it will prompt you to do so.

Also, the first launch of Purr Data needs some time -- after Rosetta does its thing, Purr Data will prompt you for access to the microphone, and it also needs to initialize the help and auto-completion indices. So some patience is needed, but afterwards subsequent launches will be quick.

**Comment by agraef** [comment]
I've updated and clarified some of the installation instructions in the wiki now so that it's hopefully easier to figure out now. Thanks for the report.
