### ISSUE TITLE
buffer overflow with Ubuntu Studio 24.04 and Pipewire configuration

### ISSUE THREAD

**Issue by transistorkreis** [agraef/purr-data#57]
I switched to Ubuntu Studio 24.04.1 LTS and installed it from scratch. And I installed Purr Data by adding the aggraef:/purr-data-jgu repository and using apt as described for xUbuntu 24.04 here:

https://software.opensuse.org/download/package?package=purr-data&project=home%3Aaggraef%3Apurr-data-jgu

It worked after I patched Purr Data's nw.js (version 0.67.1) and I configured it to use Jack. Then I used the "Ubuntu Studio Audio Configuration" tool to switch to the Pipewire configuration and set the audio configuration to buffersize 512 and samplerate 96000. When I start Purr Data now the application window closes immediately again. Starting Purr Data via command line shows that a buffer overflow is detected, see attached screenshot. Pure Data (version 0.54.1) does not show this issue.

![overflow](https://github.com/user-attachments/assets/2040ed6c-a4bb-4e5f-b8c5-8f79e4fa6d4d)

**Comment by agraef** [comment]
Thanks for reporting. I'll have to install Ubuntu Studio somewhere and see whether I can reproduce this.

**Comment by agraef** [comment]
I found and fixed a potential buffer overflow in the initialization of the Jack driver. Can you please try the 2.20.0.r5328.b8cc71e9-1 test build available at https://software.opensuse.org//download.html?project=home%3Aaggraef%3Atest&package=purr-data and see whether that fixes your problem?

**Comment by agraef** [comment]
There's yet another issue with the Jack driver arbitrarily connecting to the first Jack client, which causes lockups on one of my Linux boxes. The corresponding code makes sense with Jack proper where the `system` client will be in that spot, but not on Pipewire where that Jack client doesn't even exist. Will fix that, too.

**Comment by agraef** [comment]
Looking at the vanilla Pd code, this driver has changed a lot very recently. They now go to great lengths to try and identify a reasonable default source and sink to auto-connect to. I could backport those changes, but TBH  I think that this approach is over-engineered and offers little benefits. If you have a complicated studio setup with a lot of audio devices, Pd will most likely auto-connect to the wrong device anyway; it makes much more sense to use an audio patchbay in such situations. Most people will do that anyway when using Jack.

So I think that in order to maintain backward compatibility with "legacy" systems still running Jack proper, I'll keep the previous behavior of auto-connecting to `system` if it exists, and just skip the auto-connection otherwise (i.e., on Pipewire systems).

**Comment by agraef** [comment]
This should now all be fixed in the latest builds. I'll also update the purr-data-jgu repository shortly.

**Comment by transistorkreis** [comment]
I installed the test build and it works, i.e. there is no buffer overflow or error message at startup any more. Thank you for fixing it and for keeping Purr Data in active development! With my setup Purr Data is started first and it appears in Carla. Then Ardour is started and creates all the audio connections. Finally, jack_connect is executed once to create a MIDI connection from pd to my audio and MIDI interface. I also tested this with the test build and it works. Please notify if the purr-data-jgu repo is updated. I will switch back to it then.

**Comment by agraef** [comment]
Thanks for reporting back! The Ubuntu builds on purr-data-jgu should all be up-to-date now.
